language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew test